### ISSUE TITLE
Removal of 'select' on Trigger group throws an exception

### ISSUE THREAD

**Issue by sgraystar** [autoSteve/acMqtt#23]
Discovered by accident trying different options. I didn't like select anyway so not using now.

Create new tag under Trigger Control (202): Test trigger.
Create new levels under Test Trigger: 0=off, 255=on
Add keywords to object Test Trigger: MQTT, select, lvl=0/255, sa=ZZZ, pn=testTrigger,
Remove keywords from object Test Trigger.

Device: 5500AC2
Version: 1.15.0, hw v1.1
Script version: https://github.com/autoSteve/acMqtt/commit/1c11ad17cb19eed650605a21cf1335e1c0f391b5

MQTT final config
lighting = {['99']=true} -- lastlvl is disabled

Log extract, the 'Error checking' entry is repeated every 30 sec.
```
* string: Error checking create/update/delete: [string "Resident"]:1223: bad argument #1 to 'ipairs' (table expected, got nil)
* string: Published 1 CBus discovery and current level topic in 0.019 seconds, event scripts restarted
* string: Publishing homeassistant/select/cbus_mqtt_254_202_15/config as testTrigger in area ZZZ
* string: Queued 1 object with keyword MQTT for publication: 0/202/15
```

**Comment by autoSteve** [comment]
I suspect that this has been resolved by a commit five days ago. I could not replicate this on current code. The fix extensively involved trigger levels because I noticed it was somewhat broken for create/update/delete. That error rings a big bell in my head...

[Fix issues with level create/update/remove](https://github.com/autoSteve/acMqtt/commit/46b32e00d58d86d9a3eaab3e8fe65fe70c510d65)

**Comment by autoSteve** [comment]
Smart use of lighting = {['99']=true}, BTW, @sgraystar.

Was lastlvl causing issues?

**Comment by sgraystar** [comment]
Sorry, should have checked latest commit. Unfortunately I am still seeing the exception (different line number).

I turned off lastlvl a while ago because it had the side effect of preventing dimming level being raised from <100 to 100. I have one dimmer button I use for sonos, short press=on/off & long press=volume. While testing script changes and controlling from HA this was intercepting the on=255.
Excluding this very very corner case I am not sure lastlvl would make any difference in my setup now as HA & Homekit Bridge already seem to ramp to previous level when turning on a light. Maybe other integrations behave differently.
I only mentioned it in case it was sending the script down an execution path that is causing this exception.

Script version: https://github.com/autoSteve/acMqtt/commit/728894397bf12c030f578dad040a2bab1fe43b20

```
* string: Error checking create/update/delete: [string "Resident"]:1283: bad argument #1 to 'ipairs' (table expected, got nil)
* string: Publishing homeassistant/select/cbus_mqtt_254_202_15/config as Test in area ZZZ
``` 

MQTT explorer retained entry
```
{"stat_t":"cbus\/read\/254\/202\/15\/select","cmd_t":"cbus\/write\/254\/202\/15\/select","avty_t":"cbus\/status","options":["off","on"],"uniq_id":"cbus_mqtt_254_202_15","dev":{"ids":"ZZZ Test","mdl":"CBus","sa":"ZZZ","mf":"Schneider Electric","name":"Test"},"name":"","obj_id":"cbus_mqtt_254_202_15"}
```

**Comment by autoSteve** [comment]
Thank you so much for pointing this issue out, @sgraystar.

Turns out that trigger app selects were quite broken, and not just from a delete standpoint. They were also not reporting status to HA.

All fixed.

While looking I also noticed that some buttons were setting a status, which is nonsensical, and that is now fixed, too.

**Comment by autoSteve** [comment]
Suppressing lastLevel is now a thing, @sgraystar. One of the latest commits. I'm running in this config to see whether there are any adverse effects, and few so far, except possibly sweep fan. Telling Google "Hoy Google, turn on the fan" is setting full boar instead of it's last known setting of low/medium, so I might look to implement certain corner cases in more detail in future.

It's mostly a MQTT Final/MQTT script managed thing, as you cottoned on to. Script cleans up 'lastLevel' storage if it previously was set.

**Comment by sgraystar** [comment]
OK. I'll update later in the week.

**Comment by autoSteve** [comment]
Sweep fans back to normal, @sgraystar, saving last level just for those.

**Comment by autoSteve** [comment]
Almost. New commit @sgraystar.

**Comment by sgraystar** [comment]
All good. Thanks again.

Script verson: https://github.com/autoSteve/acMqtt/commit/f0e27e887f56e5c5a953a7d7ae16ddd95cbae9b3

```
* string: Publishing state and level cbus/read/254/56/10 to ON/255
* string: Final level achieved, 0/56/10/255
* string: Setting 0/56/10 to 255.000, previous=191.000
```
